version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    networks:
      - tba_network

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://postgres:25032025@database:5432/tba_db
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - tba_network

  database:
    image: postgres:15
    container_name: tba_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 25032025
      POSTGRES_DB: tba_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - tba_network

  nginx:
    image: nginx:alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/www/certbot:/var/www/certbot  # Thêm dòng này    
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - tba_network

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot # Thêm dòng này
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - tba_network

volumes:
  db_data:

networks:
  tba_network: