version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.production
    ports:
      - "8080:80"  # Host:8080 -> Container:80 (web server)
    networks:
      - tba_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npm run migration:run && npm run start:prod"
    env_file:
      - ./backend/.env.production
    ports:
      - "3000:3000"  # Host:3000 -> Container:3000 (NestJS app)
    volumes:
      - ./uploads:/app/uploads  # Persist uploads
    depends_on:
      database:
        condition: service_healthy
    networks:
      - tba_network
    restart: unless-stopped

  database:
    image: postgres:15
    container_name: tba_db
    env_file:
      - ./.env.db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tba_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/lib/letsencrypt/challenges:/challenges:rw
      - ./uploads:/uploads:ro  # Added: Give Nginx direct access to uploads
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - tba_network
    restart: unless-stopped

volumes:
  db_data:

networks:
  tba_network:
    driver: bridge