version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    networks:
      - tba_network

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://postgres:25032025@database:5432/tba_db
    depends_on:
      - database
    networks:
      - tba_network

  database:
    image: postgres:15
    container_name: tba_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 25032025
      POSTGRES_DB: tba_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - tba_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - tba_network

  certbot:
      image: certbot/certbot
      volumes:
        - certbot-etc:/etc/letsencrypt
        - ./nginx/static:/var/www/html:rw  # Thay đổi từ ro sang rw
      depends_on:
        - nginx
      entrypoint: ""
      command: "sh -c 'sleep 6 && certbot renew --webroot -w /var/www/html --dry-run && certbot renew --webroot -w /var/www/html'"
volumes:
  db_data:
  certbot-etc:
  certbot-web:

networks:
  tba_network:
