version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.production
    ports:
      - "8080:80"
    networks:
      - tba_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.production
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=25032025
      - POSTGRES_DB=tba_db
      # - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - tba_network
    restart: unless-stopped

  database:
    image: postgres:15
    container_name: tba_db
    env_file:
      - ./.env.db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tba_network
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/lib/letsencrypt/challenges:/challenges:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - tba_network
    restart: unless-stopped
volumes:
  db_data:

networks:
  tba_network:
